// Code generated by internal/projection/gen; DO NOT EDIT.
package projection

import "google.golang.org/protobuf/reflect/protoreflect"

const DescriptorSHA256 = "fd41c6736229ccba9a47a4311dd37be2ec39001c057d9c3cf93e23088747a41b"

type Alert struct {
	ActivePeriod       []*TimeRange      `parquet:"active_period" json:"active_period,omitempty"`
	InformedEntity     []*EntitySelector `parquet:"informed_entity" json:"informed_entity,omitempty"`
	Cause              *int32            `parquet:"cause" json:"cause,omitempty"`
	Effect             *int32            `parquet:"effect" json:"effect,omitempty"`
	Url                *TranslatedString `parquet:"url" json:"url,omitempty"`
	HeaderText         *TranslatedString `parquet:"header_text" json:"header_text,omitempty"`
	DescriptionText    *TranslatedString `parquet:"description_text" json:"description_text,omitempty"`
	TtsHeaderText      *TranslatedString `parquet:"tts_header_text" json:"tts_header_text,omitempty"`
	TtsDescriptionText *TranslatedString `parquet:"tts_description_text" json:"tts_description_text,omitempty"`
	SeverityLevel      *int32            `parquet:"severity_level" json:"severity_level,omitempty"`
}
type EntitySelector struct {
	AgencyId    *string         `parquet:"agency_id" json:"agency_id,omitempty"`
	RouteId     *string         `parquet:"route_id" json:"route_id,omitempty"`
	RouteType   *int32          `parquet:"route_type" json:"route_type,omitempty"`
	Trip        *TripDescriptor `parquet:"trip" json:"trip,omitempty"`
	StopId      *string         `parquet:"stop_id" json:"stop_id,omitempty"`
	DirectionId *uint32         `parquet:"direction_id" json:"direction_id,omitempty"`
}
type FeedEntity struct {
	Id         *string          `parquet:"id" json:"id,omitempty"`
	IsDeleted  *bool            `parquet:"is_deleted" json:"is_deleted,omitempty"`
	TripUpdate *TripUpdate      `parquet:"trip_update" json:"trip_update,omitempty"`
	Vehicle    *VehiclePosition `parquet:"vehicle" json:"vehicle,omitempty"`
	Alert      *Alert           `parquet:"alert" json:"alert,omitempty"`
}
type FeedHeader struct {
	GtfsRealtimeVersion *string `parquet:"gtfs_realtime_version" json:"gtfs_realtime_version,omitempty"`
	Incrementality      *int32  `parquet:"incrementality" json:"incrementality,omitempty"`
	Timestamp           *uint64 `parquet:"timestamp" json:"timestamp,omitempty"`
}
type FeedMessage struct {
	Header *FeedHeader   `parquet:"header" json:"header,omitempty"`
	Entity []*FeedEntity `parquet:"entity" json:"entity,omitempty"`
}
type Position struct {
	Latitude  *float32 `parquet:"latitude" json:"latitude,omitempty"`
	Longitude *float32 `parquet:"longitude" json:"longitude,omitempty"`
	Bearing   *float32 `parquet:"bearing" json:"bearing,omitempty"`
	Odometer  *float64 `parquet:"odometer" json:"odometer,omitempty"`
	Speed     *float32 `parquet:"speed" json:"speed,omitempty"`
}
type TimeRange struct {
	Start *uint64 `parquet:"start" json:"start,omitempty"`
	End   *uint64 `parquet:"end" json:"end,omitempty"`
}
type TranslatedString struct {
	Translation []*TranslatedString_Translation `parquet:"translation" json:"translation,omitempty"`
}
type TranslatedString_Translation struct {
	Text     *string `parquet:"text" json:"text,omitempty"`
	Language *string `parquet:"language" json:"language,omitempty"`
}
type TripDescriptor struct {
	TripId               *string `parquet:"trip_id" json:"trip_id,omitempty"`
	RouteId              *string `parquet:"route_id" json:"route_id,omitempty"`
	DirectionId          *uint32 `parquet:"direction_id" json:"direction_id,omitempty"`
	StartTime            *string `parquet:"start_time" json:"start_time,omitempty"`
	StartDate            *string `parquet:"start_date" json:"start_date,omitempty"`
	ScheduleRelationship *int32  `parquet:"schedule_relationship" json:"schedule_relationship,omitempty"`
}
type TripUpdate struct {
	Trip           *TripDescriptor              `parquet:"trip" json:"trip,omitempty"`
	Vehicle        *VehicleDescriptor           `parquet:"vehicle" json:"vehicle,omitempty"`
	StopTimeUpdate []*TripUpdate_StopTimeUpdate `parquet:"stop_time_update" json:"stop_time_update,omitempty"`
	Timestamp      *uint64                      `parquet:"timestamp" json:"timestamp,omitempty"`
	Delay          *int32                       `parquet:"delay" json:"delay,omitempty"`
	TripProperties *TripUpdate_TripProperties   `parquet:"trip_properties" json:"trip_properties,omitempty"`
}
type TripUpdate_StopTimeEvent struct {
	Delay       *int32 `parquet:"delay" json:"delay,omitempty"`
	Time        *int64 `parquet:"time" json:"time,omitempty"`
	Uncertainty *int32 `parquet:"uncertainty" json:"uncertainty,omitempty"`
}
type TripUpdate_StopTimeUpdate struct {
	StopSequence         *uint32                                       `parquet:"stop_sequence" json:"stop_sequence,omitempty"`
	StopId               *string                                       `parquet:"stop_id" json:"stop_id,omitempty"`
	Arrival              *TripUpdate_StopTimeEvent                     `parquet:"arrival" json:"arrival,omitempty"`
	Departure            *TripUpdate_StopTimeEvent                     `parquet:"departure" json:"departure,omitempty"`
	ScheduleRelationship *int32                                        `parquet:"schedule_relationship" json:"schedule_relationship,omitempty"`
	StopTimeProperties   *TripUpdate_StopTimeUpdate_StopTimeProperties `parquet:"stop_time_properties" json:"stop_time_properties,omitempty"`
}
type TripUpdate_StopTimeUpdate_StopTimeProperties struct {
	AssignedStopId *string `parquet:"assigned_stop_id" json:"assigned_stop_id,omitempty"`
}
type TripUpdate_TripProperties struct {
	TripId    *string `parquet:"trip_id" json:"trip_id,omitempty"`
	StartDate *string `parquet:"start_date" json:"start_date,omitempty"`
	StartTime *string `parquet:"start_time" json:"start_time,omitempty"`
}
type VehicleDescriptor struct {
	Id           *string `parquet:"id" json:"id,omitempty"`
	Label        *string `parquet:"label" json:"label,omitempty"`
	LicensePlate *string `parquet:"license_plate" json:"license_plate,omitempty"`
}
type VehiclePosition struct {
	Trip                 *TripDescriptor                    `parquet:"trip" json:"trip,omitempty"`
	Vehicle              *VehicleDescriptor                 `parquet:"vehicle" json:"vehicle,omitempty"`
	Position             *Position                          `parquet:"position" json:"position,omitempty"`
	CurrentStopSequence  *uint32                            `parquet:"current_stop_sequence" json:"current_stop_sequence,omitempty"`
	StopId               *string                            `parquet:"stop_id" json:"stop_id,omitempty"`
	CurrentStatus        *int32                             `parquet:"current_status" json:"current_status,omitempty"`
	Timestamp            *uint64                            `parquet:"timestamp" json:"timestamp,omitempty"`
	CongestionLevel      *int32                             `parquet:"congestion_level" json:"congestion_level,omitempty"`
	OccupancyStatus      *int32                             `parquet:"occupancy_status" json:"occupancy_status,omitempty"`
	OccupancyPercentage  *uint32                            `parquet:"occupancy_percentage" json:"occupancy_percentage,omitempty"`
	MultiCarriageDetails []*VehiclePosition_CarriageDetails `parquet:"multi_carriage_details" json:"multi_carriage_details,omitempty"`
}
type VehiclePosition_CarriageDetails struct {
	Id                  *string `parquet:"id" json:"id,omitempty"`
	Label               *string `parquet:"label" json:"label,omitempty"`
	OccupancyStatus     *int32  `parquet:"occupancy_status" json:"occupancy_status,omitempty"`
	OccupancyPercentage *int32  `parquet:"occupancy_percentage" json:"occupancy_percentage,omitempty"`
	CarriageSequence    *uint32 `parquet:"carriage_sequence" json:"carriage_sequence,omitempty"`
}

func projectAlert(m protoreflect.Message) *Alert {
	if !m.IsValid() {
		return nil
	}
	out := &Alert{}
	f0 := m.Descriptor().Fields().ByNumber(1)
	if f0 != nil {
		list := m.Get(f0).List()
		if list.Len() > 0 {
			out.ActivePeriod = make([]*TimeRange, 0, list.Len())
			for i := 0; i < list.Len(); i++ {
				out.ActivePeriod = append(out.ActivePeriod, projectTimeRange(list.Get(i).Message()))
			}
		}
	}
	f1 := m.Descriptor().Fields().ByNumber(5)
	if f1 != nil {
		list := m.Get(f1).List()
		if list.Len() > 0 {
			out.InformedEntity = make([]*EntitySelector, 0, list.Len())
			for i := 0; i < list.Len(); i++ {
				out.InformedEntity = append(out.InformedEntity, projectEntitySelector(list.Get(i).Message()))
			}
		}
	}
	f2 := m.Descriptor().Fields().ByNumber(6)
	if f2 != nil && m.Has(f2) {
		v := int32(m.Get(f2).Enum())
		out.Cause = &v
	}
	f3 := m.Descriptor().Fields().ByNumber(7)
	if f3 != nil && m.Has(f3) {
		v := int32(m.Get(f3).Enum())
		out.Effect = &v
	}
	f4 := m.Descriptor().Fields().ByNumber(8)
	if f4 != nil && m.Has(f4) {
		out.Url = projectTranslatedString(m.Get(f4).Message())
	}
	f5 := m.Descriptor().Fields().ByNumber(10)
	if f5 != nil && m.Has(f5) {
		out.HeaderText = projectTranslatedString(m.Get(f5).Message())
	}
	f6 := m.Descriptor().Fields().ByNumber(11)
	if f6 != nil && m.Has(f6) {
		out.DescriptionText = projectTranslatedString(m.Get(f6).Message())
	}
	f7 := m.Descriptor().Fields().ByNumber(12)
	if f7 != nil && m.Has(f7) {
		out.TtsHeaderText = projectTranslatedString(m.Get(f7).Message())
	}
	f8 := m.Descriptor().Fields().ByNumber(13)
	if f8 != nil && m.Has(f8) {
		out.TtsDescriptionText = projectTranslatedString(m.Get(f8).Message())
	}
	f9 := m.Descriptor().Fields().ByNumber(14)
	if f9 != nil && m.Has(f9) {
		v := int32(m.Get(f9).Enum())
		out.SeverityLevel = &v
	}
	return out
}
func projectEntitySelector(m protoreflect.Message) *EntitySelector {
	if !m.IsValid() {
		return nil
	}
	out := &EntitySelector{}
	f0 := m.Descriptor().Fields().ByNumber(1)
	if f0 != nil && m.Has(f0) {
		v := m.Get(f0).String()
		out.AgencyId = &v
	}
	f1 := m.Descriptor().Fields().ByNumber(2)
	if f1 != nil && m.Has(f1) {
		v := m.Get(f1).String()
		out.RouteId = &v
	}
	f2 := m.Descriptor().Fields().ByNumber(3)
	if f2 != nil && m.Has(f2) {
		v := int32(m.Get(f2).Int())
		out.RouteType = &v
	}
	f3 := m.Descriptor().Fields().ByNumber(4)
	if f3 != nil && m.Has(f3) {
		out.Trip = projectTripDescriptor(m.Get(f3).Message())
	}
	f4 := m.Descriptor().Fields().ByNumber(5)
	if f4 != nil && m.Has(f4) {
		v := m.Get(f4).String()
		out.StopId = &v
	}
	f5 := m.Descriptor().Fields().ByNumber(6)
	if f5 != nil && m.Has(f5) {
		v := uint32(m.Get(f5).Uint())
		out.DirectionId = &v
	}
	return out
}
func projectFeedEntity(m protoreflect.Message) *FeedEntity {
	if !m.IsValid() {
		return nil
	}
	out := &FeedEntity{}
	f0 := m.Descriptor().Fields().ByNumber(1)
	if f0 != nil && m.Has(f0) {
		v := m.Get(f0).String()
		out.Id = &v
	}
	f1 := m.Descriptor().Fields().ByNumber(2)
	if f1 != nil && m.Has(f1) {
		v := m.Get(f1).Bool()
		out.IsDeleted = &v
	}
	f2 := m.Descriptor().Fields().ByNumber(3)
	if f2 != nil && m.Has(f2) {
		out.TripUpdate = projectTripUpdate(m.Get(f2).Message())
	}
	f3 := m.Descriptor().Fields().ByNumber(4)
	if f3 != nil && m.Has(f3) {
		out.Vehicle = projectVehiclePosition(m.Get(f3).Message())
	}
	f4 := m.Descriptor().Fields().ByNumber(5)
	if f4 != nil && m.Has(f4) {
		out.Alert = projectAlert(m.Get(f4).Message())
	}
	return out
}
func projectFeedHeader(m protoreflect.Message) *FeedHeader {
	if !m.IsValid() {
		return nil
	}
	out := &FeedHeader{}
	f0 := m.Descriptor().Fields().ByNumber(1)
	if f0 != nil && m.Has(f0) {
		v := m.Get(f0).String()
		out.GtfsRealtimeVersion = &v
	}
	f1 := m.Descriptor().Fields().ByNumber(2)
	if f1 != nil && m.Has(f1) {
		v := int32(m.Get(f1).Enum())
		out.Incrementality = &v
	}
	f2 := m.Descriptor().Fields().ByNumber(3)
	if f2 != nil && m.Has(f2) {
		v := m.Get(f2).Uint()
		out.Timestamp = &v
	}
	return out
}
func projectFeedMessage(m protoreflect.Message) *FeedMessage {
	if !m.IsValid() {
		return nil
	}
	out := &FeedMessage{}
	f0 := m.Descriptor().Fields().ByNumber(1)
	if f0 != nil && m.Has(f0) {
		out.Header = projectFeedHeader(m.Get(f0).Message())
	}
	f1 := m.Descriptor().Fields().ByNumber(2)
	if f1 != nil {
		list := m.Get(f1).List()
		if list.Len() > 0 {
			out.Entity = make([]*FeedEntity, 0, list.Len())
			for i := 0; i < list.Len(); i++ {
				out.Entity = append(out.Entity, projectFeedEntity(list.Get(i).Message()))
			}
		}
	}
	return out
}
func ProjectFeedMessage(m protoreflect.Message) *FeedMessage { return projectFeedMessage(m) }
func projectPosition(m protoreflect.Message) *Position {
	if !m.IsValid() {
		return nil
	}
	out := &Position{}
	f0 := m.Descriptor().Fields().ByNumber(1)
	if f0 != nil && m.Has(f0) {
		v := float32(m.Get(f0).Float())
		out.Latitude = &v
	}
	f1 := m.Descriptor().Fields().ByNumber(2)
	if f1 != nil && m.Has(f1) {
		v := float32(m.Get(f1).Float())
		out.Longitude = &v
	}
	f2 := m.Descriptor().Fields().ByNumber(3)
	if f2 != nil && m.Has(f2) {
		v := float32(m.Get(f2).Float())
		out.Bearing = &v
	}
	f3 := m.Descriptor().Fields().ByNumber(4)
	if f3 != nil && m.Has(f3) {
		v := m.Get(f3).Float()
		out.Odometer = &v
	}
	f4 := m.Descriptor().Fields().ByNumber(5)
	if f4 != nil && m.Has(f4) {
		v := float32(m.Get(f4).Float())
		out.Speed = &v
	}
	return out
}
func projectTimeRange(m protoreflect.Message) *TimeRange {
	if !m.IsValid() {
		return nil
	}
	out := &TimeRange{}
	f0 := m.Descriptor().Fields().ByNumber(1)
	if f0 != nil && m.Has(f0) {
		v := m.Get(f0).Uint()
		out.Start = &v
	}
	f1 := m.Descriptor().Fields().ByNumber(2)
	if f1 != nil && m.Has(f1) {
		v := m.Get(f1).Uint()
		out.End = &v
	}
	return out
}
func projectTranslatedString(m protoreflect.Message) *TranslatedString {
	if !m.IsValid() {
		return nil
	}
	out := &TranslatedString{}
	f0 := m.Descriptor().Fields().ByNumber(1)
	if f0 != nil {
		list := m.Get(f0).List()
		if list.Len() > 0 {
			out.Translation = make([]*TranslatedString_Translation, 0, list.Len())
			for i := 0; i < list.Len(); i++ {
				out.Translation = append(out.Translation, projectTranslatedString_Translation(list.Get(i).Message()))
			}
		}
	}
	return out
}
func projectTranslatedString_Translation(m protoreflect.Message) *TranslatedString_Translation {
	if !m.IsValid() {
		return nil
	}
	out := &TranslatedString_Translation{}
	f0 := m.Descriptor().Fields().ByNumber(1)
	if f0 != nil && m.Has(f0) {
		v := m.Get(f0).String()
		out.Text = &v
	}
	f1 := m.Descriptor().Fields().ByNumber(2)
	if f1 != nil && m.Has(f1) {
		v := m.Get(f1).String()
		out.Language = &v
	}
	return out
}
func projectTripDescriptor(m protoreflect.Message) *TripDescriptor {
	if !m.IsValid() {
		return nil
	}
	out := &TripDescriptor{}
	f0 := m.Descriptor().Fields().ByNumber(1)
	if f0 != nil && m.Has(f0) {
		v := m.Get(f0).String()
		out.TripId = &v
	}
	f1 := m.Descriptor().Fields().ByNumber(5)
	if f1 != nil && m.Has(f1) {
		v := m.Get(f1).String()
		out.RouteId = &v
	}
	f2 := m.Descriptor().Fields().ByNumber(6)
	if f2 != nil && m.Has(f2) {
		v := uint32(m.Get(f2).Uint())
		out.DirectionId = &v
	}
	f3 := m.Descriptor().Fields().ByNumber(2)
	if f3 != nil && m.Has(f3) {
		v := m.Get(f3).String()
		out.StartTime = &v
	}
	f4 := m.Descriptor().Fields().ByNumber(3)
	if f4 != nil && m.Has(f4) {
		v := m.Get(f4).String()
		out.StartDate = &v
	}
	f5 := m.Descriptor().Fields().ByNumber(4)
	if f5 != nil && m.Has(f5) {
		v := int32(m.Get(f5).Enum())
		out.ScheduleRelationship = &v
	}
	return out
}
func projectTripUpdate(m protoreflect.Message) *TripUpdate {
	if !m.IsValid() {
		return nil
	}
	out := &TripUpdate{}
	f0 := m.Descriptor().Fields().ByNumber(1)
	if f0 != nil && m.Has(f0) {
		out.Trip = projectTripDescriptor(m.Get(f0).Message())
	}
	f1 := m.Descriptor().Fields().ByNumber(3)
	if f1 != nil && m.Has(f1) {
		out.Vehicle = projectVehicleDescriptor(m.Get(f1).Message())
	}
	f2 := m.Descriptor().Fields().ByNumber(2)
	if f2 != nil {
		list := m.Get(f2).List()
		if list.Len() > 0 {
			out.StopTimeUpdate = make([]*TripUpdate_StopTimeUpdate, 0, list.Len())
			for i := 0; i < list.Len(); i++ {
				out.StopTimeUpdate = append(out.StopTimeUpdate, projectTripUpdate_StopTimeUpdate(list.Get(i).Message()))
			}
		}
	}
	f3 := m.Descriptor().Fields().ByNumber(4)
	if f3 != nil && m.Has(f3) {
		v := m.Get(f3).Uint()
		out.Timestamp = &v
	}
	f4 := m.Descriptor().Fields().ByNumber(5)
	if f4 != nil && m.Has(f4) {
		v := int32(m.Get(f4).Int())
		out.Delay = &v
	}
	f5 := m.Descriptor().Fields().ByNumber(6)
	if f5 != nil && m.Has(f5) {
		out.TripProperties = projectTripUpdate_TripProperties(m.Get(f5).Message())
	}
	return out
}
func projectTripUpdate_StopTimeEvent(m protoreflect.Message) *TripUpdate_StopTimeEvent {
	if !m.IsValid() {
		return nil
	}
	out := &TripUpdate_StopTimeEvent{}
	f0 := m.Descriptor().Fields().ByNumber(1)
	if f0 != nil && m.Has(f0) {
		v := int32(m.Get(f0).Int())
		out.Delay = &v
	}
	f1 := m.Descriptor().Fields().ByNumber(2)
	if f1 != nil && m.Has(f1) {
		v := m.Get(f1).Int()
		out.Time = &v
	}
	f2 := m.Descriptor().Fields().ByNumber(3)
	if f2 != nil && m.Has(f2) {
		v := int32(m.Get(f2).Int())
		out.Uncertainty = &v
	}
	return out
}
func projectTripUpdate_StopTimeUpdate(m protoreflect.Message) *TripUpdate_StopTimeUpdate {
	if !m.IsValid() {
		return nil
	}
	out := &TripUpdate_StopTimeUpdate{}
	f0 := m.Descriptor().Fields().ByNumber(1)
	if f0 != nil && m.Has(f0) {
		v := uint32(m.Get(f0).Uint())
		out.StopSequence = &v
	}
	f1 := m.Descriptor().Fields().ByNumber(4)
	if f1 != nil && m.Has(f1) {
		v := m.Get(f1).String()
		out.StopId = &v
	}
	f2 := m.Descriptor().Fields().ByNumber(2)
	if f2 != nil && m.Has(f2) {
		out.Arrival = projectTripUpdate_StopTimeEvent(m.Get(f2).Message())
	}
	f3 := m.Descriptor().Fields().ByNumber(3)
	if f3 != nil && m.Has(f3) {
		out.Departure = projectTripUpdate_StopTimeEvent(m.Get(f3).Message())
	}
	f4 := m.Descriptor().Fields().ByNumber(5)
	if f4 != nil && m.Has(f4) {
		v := int32(m.Get(f4).Enum())
		out.ScheduleRelationship = &v
	}
	f5 := m.Descriptor().Fields().ByNumber(6)
	if f5 != nil && m.Has(f5) {
		out.StopTimeProperties = projectTripUpdate_StopTimeUpdate_StopTimeProperties(m.Get(f5).Message())
	}
	return out
}
func projectTripUpdate_StopTimeUpdate_StopTimeProperties(m protoreflect.Message) *TripUpdate_StopTimeUpdate_StopTimeProperties {
	if !m.IsValid() {
		return nil
	}
	out := &TripUpdate_StopTimeUpdate_StopTimeProperties{}
	f0 := m.Descriptor().Fields().ByNumber(1)
	if f0 != nil && m.Has(f0) {
		v := m.Get(f0).String()
		out.AssignedStopId = &v
	}
	return out
}
func projectTripUpdate_TripProperties(m protoreflect.Message) *TripUpdate_TripProperties {
	if !m.IsValid() {
		return nil
	}
	out := &TripUpdate_TripProperties{}
	f0 := m.Descriptor().Fields().ByNumber(1)
	if f0 != nil && m.Has(f0) {
		v := m.Get(f0).String()
		out.TripId = &v
	}
	f1 := m.Descriptor().Fields().ByNumber(2)
	if f1 != nil && m.Has(f1) {
		v := m.Get(f1).String()
		out.StartDate = &v
	}
	f2 := m.Descriptor().Fields().ByNumber(3)
	if f2 != nil && m.Has(f2) {
		v := m.Get(f2).String()
		out.StartTime = &v
	}
	return out
}
func projectVehicleDescriptor(m protoreflect.Message) *VehicleDescriptor {
	if !m.IsValid() {
		return nil
	}
	out := &VehicleDescriptor{}
	f0 := m.Descriptor().Fields().ByNumber(1)
	if f0 != nil && m.Has(f0) {
		v := m.Get(f0).String()
		out.Id = &v
	}
	f1 := m.Descriptor().Fields().ByNumber(2)
	if f1 != nil && m.Has(f1) {
		v := m.Get(f1).String()
		out.Label = &v
	}
	f2 := m.Descriptor().Fields().ByNumber(3)
	if f2 != nil && m.Has(f2) {
		v := m.Get(f2).String()
		out.LicensePlate = &v
	}
	return out
}
func projectVehiclePosition(m protoreflect.Message) *VehiclePosition {
	if !m.IsValid() {
		return nil
	}
	out := &VehiclePosition{}
	f0 := m.Descriptor().Fields().ByNumber(1)
	if f0 != nil && m.Has(f0) {
		out.Trip = projectTripDescriptor(m.Get(f0).Message())
	}
	f1 := m.Descriptor().Fields().ByNumber(8)
	if f1 != nil && m.Has(f1) {
		out.Vehicle = projectVehicleDescriptor(m.Get(f1).Message())
	}
	f2 := m.Descriptor().Fields().ByNumber(2)
	if f2 != nil && m.Has(f2) {
		out.Position = projectPosition(m.Get(f2).Message())
	}
	f3 := m.Descriptor().Fields().ByNumber(3)
	if f3 != nil && m.Has(f3) {
		v := uint32(m.Get(f3).Uint())
		out.CurrentStopSequence = &v
	}
	f4 := m.Descriptor().Fields().ByNumber(7)
	if f4 != nil && m.Has(f4) {
		v := m.Get(f4).String()
		out.StopId = &v
	}
	f5 := m.Descriptor().Fields().ByNumber(4)
	if f5 != nil && m.Has(f5) {
		v := int32(m.Get(f5).Enum())
		out.CurrentStatus = &v
	}
	f6 := m.Descriptor().Fields().ByNumber(5)
	if f6 != nil && m.Has(f6) {
		v := m.Get(f6).Uint()
		out.Timestamp = &v
	}
	f7 := m.Descriptor().Fields().ByNumber(6)
	if f7 != nil && m.Has(f7) {
		v := int32(m.Get(f7).Enum())
		out.CongestionLevel = &v
	}
	f8 := m.Descriptor().Fields().ByNumber(9)
	if f8 != nil && m.Has(f8) {
		v := int32(m.Get(f8).Enum())
		out.OccupancyStatus = &v
	}
	f9 := m.Descriptor().Fields().ByNumber(10)
	if f9 != nil && m.Has(f9) {
		v := uint32(m.Get(f9).Uint())
		out.OccupancyPercentage = &v
	}
	f10 := m.Descriptor().Fields().ByNumber(11)
	if f10 != nil {
		list := m.Get(f10).List()
		if list.Len() > 0 {
			out.MultiCarriageDetails = make([]*VehiclePosition_CarriageDetails, 0, list.Len())
			for i := 0; i < list.Len(); i++ {
				out.MultiCarriageDetails = append(out.MultiCarriageDetails, projectVehiclePosition_CarriageDetails(list.Get(i).Message()))
			}
		}
	}
	return out
}
func projectVehiclePosition_CarriageDetails(m protoreflect.Message) *VehiclePosition_CarriageDetails {
	if !m.IsValid() {
		return nil
	}
	out := &VehiclePosition_CarriageDetails{}
	f0 := m.Descriptor().Fields().ByNumber(1)
	if f0 != nil && m.Has(f0) {
		v := m.Get(f0).String()
		out.Id = &v
	}
	f1 := m.Descriptor().Fields().ByNumber(2)
	if f1 != nil && m.Has(f1) {
		v := m.Get(f1).String()
		out.Label = &v
	}
	f2 := m.Descriptor().Fields().ByNumber(3)
	if f2 != nil && m.Has(f2) {
		v := int32(m.Get(f2).Enum())
		out.OccupancyStatus = &v
	}
	f3 := m.Descriptor().Fields().ByNumber(4)
	if f3 != nil && m.Has(f3) {
		v := int32(m.Get(f3).Int())
		out.OccupancyPercentage = &v
	}
	f4 := m.Descriptor().Fields().ByNumber(5)
	if f4 != nil && m.Has(f4) {
		v := uint32(m.Get(f4).Uint())
		out.CarriageSequence = &v
	}
	return out
}
